### ISSUE TITLE
🔐 DevSecOps: Automated Security Scanning Integration

### ISSUE THREAD

**Issue by dc24aicrew** [dc24aicrew/copilot-demo-spring-taskmanager#15]
### Description
The application currently lacks automated security scanning in its CI/CD pipeline, leaving potential vulnerabilities undetected until production. This issue focuses on implementing comprehensive security scanning tools and DevSecOps practices to identify vulnerabilities early in the development lifecycle.

### Current Security Scanning Gaps
**Location:** CI/CD pipeline and development workflow
**Risk Level:** High - Undetected vulnerabilities reaching production
**Missing Security Tools:**
- No OWASP dependency vulnerability scanning
- No static application security testing (SAST)
- No dynamic application security testing (DAST)
- No container security scanning
- No infrastructure as code security scanning
- No secrets detection in codebase

#### 1. 🔍 **Static Application Security Testing (SAST)**
**Current State:** No static code analysis for security
**Required Implementation:**
- [ ] SonarQube integration with security rules
- [ ] SpotBugs with security bug detection
- [ ] Checkmarx or Veracode integration
- [ ] Custom security rule definitions
- [ ] IDE integration for developer feedback

#### 2. 📦 **Dependency Vulnerability Scanning**
**Current State:** No dependency security analysis
**Required Tools:**
- [ ] OWASP Dependency-Check integration
- [ ] Snyk vulnerability scanning
- [ ] GitHub Dependabot security alerts
- [ ] Maven security plugin
- [ ] Automated dependency updates

#### 3. 🐳 **Container Security Scanning**
**Current State:** No container image security analysis
**Required Implementation:**
- [ ] Trivy container vulnerability scanner
- [ ] Docker image security scanning
- [ ] Base image vulnerability assessment
- [ ] Runtime security monitoring
- [ ] Image signing and verification

#### 4. 🌐 **Dynamic Application Security Testing (DAST)**
**Current State:** No runtime security testing
**Required Tools:**
- [ ] OWASP ZAP integration
- [ ] Burp Suite Professional automation
- [ ] Custom security test automation
- [ ] API security testing
- [ ] Authentication bypass testing

##### A. SonarQube Security Integration
```xml
<!-- pom.xml SonarQube configuration -->
<plugin>
    <groupId>org.sonarsource.scanner.maven</groupId>
    <artifactId>sonar-maven-plugin</artifactId>
    <version>3.9.1.2184</version>
    <configuration>
        <sonar.projectKey>task-manager-security</sonar.projectKey>
        <sonar.host.url>${SONAR_HOST_URL}</sonar.host.url>
        <sonar.login>${SONAR_TOKEN}</sonar.login>
        <sonar.java.binaries>target/classes</sonar.java.binaries>
        <sonar.coverage.jacoco.xmlReportPaths>target/site/jacoco/jacoco.xml</sonar.coverage.jacoco.xmlReportPaths>
        <sonar.exclusions>
            **/*Test.java,
            **/*Tests.java,
            **/test/**,
            **/target/**
        </sonar.exclusions>
    </configuration>
</plugin>
```

##### B. SpotBugs Security Rules
```xml
<plugin>
    <groupId>com.github.spotbugs</groupId>
    <artifactId>spotbugs-maven-plugin</artifactId>
    <version>4.7.3.0</version>
    <configuration>
        <effort>Max</effort>
        <threshold>Low</threshold>
        <includeFilterFile>spotbugs-security-include.xml</includeFilterFile>
        <plugins>
            <plugin>
                <groupId>com.h3xstream.findsecbugs</groupId>
                <artifactId>findsecbugs-plugin</artifactId>
                <version>1.12.0</version>
            </plugin>
        </plugins>
    </configuration>
    <executions>
        <execution>
            <goals>
                <goal>check</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

##### A. OWASP Dependency-Check
```xml
<plugin>
    <groupId>org.owasp</groupId>
    <artifactId>dependency-check-maven</artifactId>
    <version>8.4.0</version>
    <configuration>
        <format>ALL</format>
        <outputDirectory>target/dependency-check-report</outputDirectory>
        <failBuildOnCVSS>7</failBuildOnCVSS>
        <suppressionFile>owasp-dependency-check-suppressions.xml</suppressionFile>
        <assemblyAnalyzerEnabled>false</assemblyAnalyzerEnabled>
        <nodeAnalyzerEnabled>false</nodeAnalyzerEnabled>
        <yarnAuditAnalyzerEnabled>false</yarnAuditAnalyzerEnabled>
        <centralAnalyzerEnabled>true</centralAnalyzerEnabled>
    </configuration>
    <executions>
        <execution>
            <goals>
                <goal>check</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

##### B. Snyk Integration
```yaml
# .github/workflows/security-scan.yml
name: Security Scanning

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  snyk-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --fail-on=all
          
      - name: Upload Snyk report to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: snyk.sarif
```

##### A. Trivy Scanner Integration
```dockerfile
# Multi-stage Docker build with security scanning
FROM maven:3.9-openjdk-17 AS build
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Security scanning stage
FROM aquasec/trivy:latest AS security-scan
COPY --from=build target/*.jar app.jar
RUN trivy filesystem --exit-code 1 --severity HIGH,CRITICAL .

# Runtime stage with minimal base image
FROM openjdk:17-jre-slim
COPY --from=build target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app.jar"]
```

##### B. Container Security Pipeline
```yaml
# .github/workflows/container-security.yml
name: Container Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  container-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build Docker image
        run: docker build -t task-manager:${{ github.sha }} .
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'task-manager:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
```

##### A. OWASP ZAP Automation
```yaml
# .github/workflows/dast-scan.yml
name: DAST Security Testing

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM
  workflow_dispatch:

jobs:
  dast-scan:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Start application
        run: |
          docker-compose up -d
          sleep 30  # Wait for application to start
          
      - name: Run OWASP ZAP baseline scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:8080'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          
      - name: Upload ZAP scan results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: zap-scan-results
          path: report_html.html
```

##### B. API Security Testing
```java
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@TestPropertySource(properties = {
    "spring.datasource.url=jdbc:h2:mem:sectest"
})
class ApiSecurityTest {
    
    @Autowired
    private TestRestTemplate restTemplate;
    
    @Test
    void shouldRejectSqlInjectionAttempts() {
        // Test SQL injection in various parameters
        String[] sqlInjectionPayloads = {
            "'; DROP TABLE users; --",
            "' OR '1'='1",
            "'; UPDATE users SET password='hacked'; --"
        };
        
        for (String payload : sqlInjectionPayloads) {
            ResponseEntity<String> response = restTemplate.getForEntity(
                "/api/users?search=" + payload, String.class);
            
            // Should return 400 Bad Request or 422 Unprocessable Entity
            assertThat(response.getStatusCode().is4xxClientError()).isTrue();
        }
    }
    
    @Test
    void shouldRejectXssAttempts() {
        String[] xssPayloads = {
            "<script>alert('xss')</script>",
            "javascript:alert('xss')",
            "<img src=x onerror=alert('xss')>"
        };
        
        for (String payload : xssPayloads) {
            CreateUserRequest request = CreateUserRequest.builder()
                .username("testuser")
                .email("test@example.com")
                .firstName(payload)
                .lastName("User")
                .password("Test@123")
                .build();
            
            ResponseEntity<String> response = restTemplate.postForEntity(
                "/api/users", request, String.class);
                
            assertThat(response.getStatusCode().is4xxClientError()).isTrue();
        }
    }
}
```

#### A. GitHub Actions Security Workflow
```yaml
# .github/workflows/comprehensive-security.yml
name: Comprehensive Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 1 * * 1'  # Weekly on Monday at 1 AM

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          
      # SAST Scanning
      - name: Run SonarQube analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar
        
      - name: Run SpotBugs security analysis
        run: mvn spotbugs:check
        
      # Dependency Scanning
      - name: Run OWASP Dependency Check
        run: mvn org.owasp:dependency-check-maven:check
        
      - name: Run Snyk vulnerability scan
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=medium
          
      # Secrets Scanning
      - name: Run secrets detection
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: main
          head: HEAD
          
      # Container Security
      - name: Build Docker image
        run: docker build -t security-scan:latest .
        
      - name: Run container security scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'security-scan:latest'
          format: 'sarif'
          output: 'container-scan.sarif'
          
      # Upload all results
      - name: Upload SARIF files
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: '.'
```

#### B. Quality Gates Configuration
```xml
<!-- quality-gates.xml for SonarQube -->
<quality-gates>
    <gate name="Security Gate">
        <conditions>
            <condition metric="security_rating" operator="GREATER_THAN" error="1"/>
            <condition metric="reliability_rating" operator="GREATER_THAN" error="1"/>
            <condition metric="maintainability_rating" operator="GREATER_THAN" error="1"/>
            <condition metric="coverage" operator="LESS_THAN" error="80"/>
            <condition metric="duplicated_lines_density" operator="GREATER_THAN" error="3"/>
            <condition metric="vulnerabilities" operator="GREATER_THAN" error="0"/>
            <condition metric="security_hotspots" operator="GREATER_THAN" error="0"/>
        </conditions>
    </gate>
</quality-gates>
```

#### A. Security Metrics Collection
```java
@Component
public class SecurityMetricsCollector {
    
    private final MeterRegistry meterRegistry;
    
    @EventListener
    public void handleSecurityViolation(SecurityViolationEvent event) {
        Counter.builder("security.violations")
            .tag("type", event.getViolationType())
            .tag("severity", event.getSeverity())
            .register(meterRegistry)
            .increment();
            
        if (event.getSeverity() == SecuritySeverity.CRITICAL) {
            alertingService.triggerSecurityAlert(event);
        }
    }
    
    @EventListener
    public void handleVulnerabilityDetected(VulnerabilityDetectedEvent event) {
        Gauge.builder("security.vulnerabilities.count")
            .tag("severity", event.getSeverity())
            .tag("source", event.getSource())
            .register(meterRegistry, event, VulnerabilityDetectedEvent::getCount);
    }
}
```

#### B. Security Dashboard
```java
@RestController
@RequestMapping("/api/admin/security")
@PreAuthorize("hasRole('SECURITY_ADMIN')")
public class SecurityDashboardController {
    
    @GetMapping("/dashboard")
    public ResponseEntity<SecurityDashboard> getSecurityDashboard() {
        SecurityDashboard dashboard = SecurityDashboard.builder()
            .vulnerabilityCount(vulnerabilityService.getActiveVulnerabilityCount())
            .lastScanResults(scanResultService.getLatestScanResults())
            .securityMetrics(securityMetricsService.getCurrentMetrics())
            .complianceStatus(complianceService.getComplianceStatus())
            .build();
            
        return ResponseEntity.ok(dashboard);
    }
    
    @GetMapping("/scan-results/{scanId}")
    public ResponseEntity<ScanResult> getScanResult(@PathVariable String scanId) {
        ScanResult result = scanResultService.getScanResult(scanId);
        return ResponseEntity.ok(result);
    }
}
```

#### A. Security Scanning Configuration
```yaml
security:
  scanning:
    enabled: true
    schedule:
      dependency-check: "0 2 * * *"  # Daily at 2 AM
      container-scan: "0 3 * * 1"    # Weekly on Monday at 3 AM
      dast-scan: "0 1 * * 6"         # Weekly on Saturday at 1 AM
    thresholds:
      fail-build-on-critical: true
      fail-build-on-high: true
      fail-build-on-medium: false
    notifications:
      slack:
        webhook-url: ${SECURITY_SLACK_WEBHOOK}
        enabled: true
      email:
        recipients:
          - security-team@company.com
          - devops@company.com
        enabled: true
    tools:
      sonarqube:
        url: ${SONAR_HOST_URL}
        token: ${SONAR_TOKEN}
        project-key: "task-manager"
      snyk:
        token: ${SNYK_TOKEN}
        organization: ${SNYK_ORG}
      trivy:
        enabled: true
        cache-dir: "/tmp/trivy-cache"
```

#### B. Vulnerability Management
```java
@Entity
@Table(name = "security_vulnerabilities")
public class SecurityVulnerability {
    
    @Id
    private String id;
    
    @Column(name = "cve_id")
    private String cveId;
    
    @Enumerated(EnumType.STRING)
    private VulnerabilitySeverity severity;
    
    @Column(name = "component_name")
    private String componentName;
    
    @Column(name = "component_version")
    private String componentVersion;
    
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;
    
    @Enumerated(EnumType.STRING)
    private VulnerabilityStatus status;
    
    @Column(name = "detected_at")
    private LocalDateTime detectedAt;
    
    @Column(name = "resolved_at")
    private LocalDateTime resolvedAt;
    
    @Column(name = "false_positive")
    private boolean falsePositive;
    
    @Column(name = "suppression_reason")
    private String suppressionReason;
}
```

#### Security Pipeline Requirements
- [ ] All security scans integrated into CI/CD pipeline
- [ ] Security gates preventing vulnerable code deployment
- [ ] Automated vulnerability detection and alerting
- [ ] Regular security scanning scheduled
- [ ] Security metrics collection and monitoring

#### Vulnerability Management
- [ ] Comprehensive vulnerability tracking
- [ ] False positive suppression mechanism
- [ ] Remediation workflow implementation
- [ ] Security team notification system
- [ ] Compliance reporting capabilities

#### Performance Requirements
- [ ] Security scans complete within acceptable time limits
- [ ] Minimal impact on build pipeline performance
- [ ] Efficient vulnerability database updates
- [ ] Scalable scanning for multiple environments

### Priority
🔴 **High** - Essential for secure software development lifecycle

### Estimated Effort
Medium (2-3 weeks) - Comprehensive security scanning implementation

### Dependencies
- SonarQube server setup and configuration
- Snyk account and API tokens
- Security team training and processes
- Container registry integration

### Related Issues
- Part of #2 (Security Vulnerabilities \u0026 Performance Issues)
- Complements all other security issues (#5, #6, #7, #9, #14)
- Foundation for DevSecOps practices
